version: '3.8'

services:
  db:
    image: postgres:13
    container_name: zombieplus_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dbname  # Certifique-se de que o nome do banco de dados está correto
    volumes:
      - zombieplus_data:/var/lib/postgresql/data  # Usando um volume nomeado
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zombieplus_network

  api:
    build:
      context: ./apps/zombieplus/api
      dockerfile: Dockerfile
    container_name: zombieplus_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_DIALECT: postgres
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: 1234
      DB_NAME: dbname
    ports:
      - "3333:3333"
    # volumes:
    #   - ./apps/zombieplus/api:/usr/src/app
    networks:
      - zombieplus_network

  web:
    build:
      context: ./apps/zombieplus/web
      dockerfile: Dockerfile
    container_name: zombieplus_web
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:3333
    volumes:
      - ./apps/zombieplus/web:/usr/src/app
    command: npm run dev
    networks:
      - zombieplus_network
  
  sonarqube_db:
    image: postgres:13
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    networks:
      - zombieplus_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - zombieplus_network

networks:
  zombieplus_network:
    driver: bridge

volumes:
  zombieplus_data:
  sonarqube_db_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
