name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      network_id: ${{ steps.network_id.outputs.network }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Instalação docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Criar rede Docker compartilhada
        id: network_id
        run: |
          docker network create my_shared_network
          echo "::set-output name=network::my_shared_network"

      - name: Inicializar a aplicação no Docker com rede compartilhada
        run: |
          docker-compose up --build -d

      - name: Verificar se o container API está em execução
        run: |
          docker-compose ps
          docker-compose ps api
          
      - name: Esperar API ficar disponível (10 tentativas)
        run: |
          max_attempts=10
          count=0
          until curl --output /dev/null --silent --head --fail http://localhost:3333; do
            count=$((count + 1))
            if [ $count -ge $max_attempts ]; then
              echo "A API não ficou disponível após $max_attempts tentativas."
              exit 1
            fi
            echo "Aguardando a API estar disponível... Tentativa $count de $max_attempts."
            sleep 5
          done

  tests:
    runs-on: ubuntu-latest
    needs: setup # Depende do job de setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Instalação docker compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Verificar status da API novamente
        run: |
          max_attempts=10
          count=0
          until curl --output /dev/null --silent --head --fail http://localhost:3333; do
            count=$((count + 1))
            if [ $count -ge $max_attempts ]; then
              echo "A API não ficou disponível após $max_attempts tentativas."
              exit 1
            fi
            echo "Aguardando a API estar disponível... Tentativa $count de $max_attempts."
            sleep 5
          done

      - name: Análise de Código com SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=EderCuer_projeto-cypress
            -Dsonar.organization=edercuer
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Instalação das dependências
        run: npm install

      - name: Execução dos testes
        run: npm run cy:regression

  teardown:
    runs-on: ubuntu-latest
    needs: tests # Depende do job de testes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Finalizar containers e remover rede
        run: |
          docker-compose down
          docker network rm my_shared_network
