name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Step 4: Build and run Docker Compose
      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      # Step 5: Wait for services to be ready
      - name: Wait for API to be available
        run: |
          max_attempts=10
          count=0
          until curl --output /dev/null --silent --head --fail http://localhost:3333; do
            count=$((count + 1))
            if [ $count -ge $max_attempts ]; then
              echo "A API não ficou disponível após $max_attempts tentativas."
              exit 1
            fi
            echo "Aguardando a API estar disponível... Tentativa $count de $max_attempts."
            sleep 5
          done

      # Step 6: Install Cypress dependencies
      - name: Install Cypress dependencies
        run: npm install cypress --save-dev

      # Step 7: Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run

      # Step 8: Tear down Docker Compose
      - name: Tear down Docker Compose
        run: docker-compose down