name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      # Step 4: Build and run Docker Compose
      - name: Build and run Docker Compose
        run: docker-compose up --build -d

      # Step 5: Wait for services to be ready
      - name: Wait for services to be ready
        run: |
          # Aguarda a API estar disponível
          until curl --output /dev/null --silent --head --fail http://localhost:3333; do
            echo "Aguardando a API estar disponível..."
            sleep 5
          done
          # Aguarda a aplicação web estar disponível
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            echo "Aguardando a aplicação web estar disponível..."
            sleep 5
          done
      
      # Show logs (for debugging)
      - name: Show API logs
        run: docker-compose logs api

      # Step 6: Run tests
      - name: Run tests
        run: docker-compose exec api npm test

      # Step 7: Tear down Docker Compose
      - name: Tear down Docker Compose
        run: docker-compose down
